#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use CQ\CLI\CLI;
use CQ\Config\Config;

$config = new Config(__DIR__ . '/bootstrap');
$config->attach('api');
$config->attach('app');
$config->attach('secrets');

$cli = new CLI();

$cli->command('demo', [new App\Commands\Demo(), 'demo'])
    ->descriptions('Demo command');

$cli->command('app:key', [new CQ\CLI\App(), 'key'])
    ->descriptions('Generate app key used for encryption');

$cli->command('app:contextKey context', [new CQ\CLI\App(), 'contextKey'])
    ->descriptions('Derive key from app_key using context', [
        'context' => 'Context for key e.g. (Client Secret)',
    ]);

$cli->command('db:migrate [--fresh]', [new CQ\CLI\DB(), 'migrate'])
    ->descriptions('Migrate database tables', [
        '--fresh' => 'Reset DB before running migrations',
    ]);

$cli->command('db:seed', [new CQ\CLI\DB(), 'seed'])
    ->descriptions('Seed database tables');

$cli->command('make:migration [name]', [new CQ\CLI\Make(), 'migration'])
    ->descriptions('Create database migration', [
        'name' => 'Name of migration e.g. (CreateUsersTable)',
    ]);

$cli->command('make:seed name', [new CQ\CLI\Make(), 'seed'])
    ->descriptions('Create database seeder', [
        'name' => 'Name of seeder e.g. (UsersSeeder)',
    ]);

$cli->command('secrets:create', [new CQ\CLI\Secrets(), 'createStore'])
    ->descriptions('Generate secret store');

$cli->command('secrets:delete', [new CQ\CLI\Secrets(), 'deleteStore'])
    ->descriptions('Delete secret store');

$cli->run();
